### ISSUE TITLE
[FEATURE] From To Date selection as a replacement for created

### ISSUE THREAD

**Issue by gepparta** [DevEpos/eclipse-adt-plugins#16]
### Checklist

- [X] I searched existing issues and no one else requests similar feature.
- [X] I think that 25%+ users are positive towards this feature.

### Plug-in

ABAP Search and Analysis Tools

### Describe the feature

When searching for SAP CDS, you want to be guided by the latest coding examples. 
To do this, it is important to filter out the most recent results from a large number of results. 
This function would make it possible. 
The current function (created:last-year) is unfortunately not sufficient in many cases.

**Comment by stockbal** [comment]
Hi @gepparta,

the date filters are actually quite flexible:

e.g. today = 20.11.24

|Date Filter|Resulting Range|
|-----------|------------------|
|2024 | 1.1.24 - 31.12.24 |
|3.2024 | 1.3.24 - 31.3.24 |
|2023...2024 | 1.1.23 - 31.12.24|
|>last-year | > 20.11.23|
|>last-month | > 20.10.23|
|last-year...today | 20.11.23 - 20.11.24|

So the relative filters are currently not completely aligned with fixed month/year filters, as they always represent a concrete date and not a range. 
But together with comparison operators (`>`,>=`,`<`,`<=`) and the range operator `...` you have a lot of options also with the relative filters like (last-year, 2-years-ago, 3-weeks-ago, ...). You can even prefix a pattern with `!` to exclude a certain date or range. 

You can read up about it if you open the help section in eclipse as well:
![image](https://github.com/user-attachments/assets/e4c9a683-8ee1-4865-9d56-82e7758090d6)

Please let me know if that fullfills your needs,

Kind regards,
Ludwig

**Comment by gepparta** [comment]
Hello Ludwig,
I was hoping for such an answer.
That will help me. Thank you.

Unfortunately, I didn't think to look in the ADT help. 
Instead, I tried to find this info on GitHub and on DevEpos PlugIn website. 

Feel free to close the ticket and keep up the amazing work with your ADT PlugIns!

Kind regards
Alex

**Comment by stockbal** [comment]
Hi Alex,

I plan to add the eclipse documentation also to devepos.com, but I don't seem to have the time to do it 😊.

Kind regards,
Ludwig
