### ISSUE TITLE
Updatesite down?

### ISSUE THREAD

**Issue by se38** [DevEpos/eclipse-adt-plugins#9]
Currently the update site could not be found. The beta site works.

Beta okay
![beta](https://github.com/DevEpos/eclipse-adt-plugins/assets/5384144/db03058d-e537-4b47-b3f2-464b6288750d)

Latest not found
![latest](https://github.com/DevEpos/eclipse-adt-plugins/assets/5384144/6f248c84-5cf5-4e9a-888e-c4565b8b81e2)

Cheers, Uwe

**Comment by stockbal** [comment]
Hi @se38,

sorry, I somehow missed this issue. I am not sure why the dev update site was not reachable.
But both "dev" and "latest" should work now.

Regards,
Ludwig

**Comment by se38** [comment]
Works again, thank you.
